// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcileanckkztnolzntjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWxlYW5ja2t6dG5vbHpudGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTg1NzcsImV4cCI6MjA2Nzg3NDU3N30.xzD7FcAQXrNjBJ9qMwI7xliu3M70DA0Y2ei0BQBgJZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});